import ctypes
from ctypes import wintypes
import winUser
import NVDAObjects.IAccessible
import controlTypes

# Define the Windows API functions prototypes
user32 = ctypes.WinDLL('user32', use_last_error=True)

# Functions to list and get the text text
EnumWindows = user32.EnumWindows
EnumWindows.argtypes = [
	ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM),
	wintypes.LPARAM
]
EnumWindows.restype = wintypes.BOOL


IsWindowVisible = user32.IsWindowVisible
IsWindowVisible.	argtypes = [wintypes.HWND]
IsWindowVisible.restype = wintypes.BOOL

GetWindowTextLengthW = user32.GetWindowTextLengthW
GetWindowTextLengthW.argtypes = [wintypes.HWND]
GetWindowTextLengthW.restype = wintypes.INT

GetWindowTextW = user32.GetWindowTextW
GetWindowTextW.argtypes = [wintypes.HWND, wintypes.LPWSTR, wintypes.INT]
GetWindowTextW.restype = wintypes.INT

import ctypes
from ctypes import wintypes

# Load required functions from Windows User32 API
user32 = ctypes.windll.user32

# Win32 API function prototypes
EnumWindows = user32.EnumWindows
EnumWindowsProc = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)
IsWindowVisible = user32.IsWindowVisible
GetWindowTextW = user32.GetWindowTextW
GetWindowTextLengthW = user32.GetWindowTextLengthW


# Load required Windows API libraries
# user32 = ctypes.windll.user32
kernel32 = ctypes.windll.kernel32

# Win32 API function prototypes
# EnumWindows = user32.EnumWindows
# EnumWindowsProc = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)
# IsWindowVisible = user32.IsWindowVisible
GetWindowThreadProcessId = user32.GetWindowThreadProcessId
OpenProcess = kernel32.OpenProcess
CloseHandle = kernel32.CloseHandle
QueryFullProcessImageNameW = kernel32.QueryFullProcessImageNameW

# Process access rights
PROCESS_QUERY_LIMITED_INFORMATION = 0x1000


def findWindowByProcessName(pName="thunderbird.exe"):
	"""
	Iterates through visible top-level windows and returns the HWND of the first one
	belonging to the specified process name. Returns 0 if not found.
	"""
	foundHwnd = 0
	targetProcessName = pName.lower()

	def enumWindowsCallback(hwnd, lparam):
		nonlocal foundHwnd

		# Check if the window is visible
		if IsWindowVisible(hwnd):
			pid = wintypes.DWORD()
			GetWindowThreadProcessId(hwnd, ctypes.byref(pid))

			if pid.value != 0:
				# Open process to query its executable path
				hProcess = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, False, pid.value)
				if hProcess:
					try:
						bufferSize = wintypes.DWORD(1024)
						buffer = ctypes.create_unicode_buffer(bufferSize.value)
						
						if QueryFullProcessImageNameW(hProcess, 0, buffer, ctypes.byref(bufferSize)):
							# Extract executable name from full path
							exePath = buffer.value
							exeName = exePath.rsplit('\\', 1)[-1].lower()

							if exeName == targetProcessName:
								foundHwnd = hwnd
								return False  # Stop enumeration immediately
					finally:
						CloseHandle(hProcess)

		return True  # Continue enumeration

	# Execute window enumeration
	EnumWindows(EnumWindowsProc(enumWindowsCallback), 0)

	return foundHwnd


def findWindowByTitleEnding(titleEnd):
	"""
	Iterates through visible windows and returns the HWND of the first one
	whose title ends with `titleEnd`. Returns 0 if not found.
	"""
	found_hwnd = 0

	def enum_windows_callback(hwnd, lparam):
		nonlocal found_hwnd

		# Check if the window is visible
		if IsWindowVisible(hwnd):
			# Retrieve the window title length
			length = GetWindowTextLengthW(hwnd)
			if length > 0:
				buffer = ctypes.create_unicode_buffer(length + 1)
				GetWindowTextW(hwnd, buffer, length + 1)
				title = buffer.value

				# Check if the title ends with the specified substring
				if title.endswith(titleEnd):
					found_hwnd = hwnd
					return False  # Stop enumeration immediately

		return True  # Continue enumeration

	# Execute window enumeration
	EnumWindows(EnumWindowsProc(enum_windows_callback), 0)

	return found_hwnd

import psutil
# generated by Gemini 
# def getProcessName(hwnd):
	# if not hwnd:
		# return ""

	# # 2. Get the PID associated with the handle
	# pid = wintypes.DWORD()
	# ctypes.windll.user32.GetWindowThreadProcessId(hwnd, ctypes.byref(pid))
	
	# # 3. Get the process name from the PID
	# try:
		# process = psutil.Process(pid.value)
		# return process.name()
	# except (psutil.NoSuchProcess, psutil.AccessDenied):
		# return ""

# def findWindowByProcessName(procName):
	# foundWindow = 0

	# @ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)
	# def enum_windows_callback(hwnd, lParam):
		# if IsWindowVisible(hwnd):
			# if getProcessName(hwnd) == procName:
				# foundWindow = hwnd
				# return False # stop enumeration 
		# return True
	# EnumWindows(enum_windows_callback, 0)
	# return foundWindow


# Define the C callback signature for EnumWindows: BOOL Callback(HWND hwnd, LPARAM lParam)
WNDENUMPROC = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)


def findTBWindowObjects(winTitle="Mozilla Thunderbird", mainOnly=False):
	matchingObjects = []

	def enumWindowsCallback(hwnd, lParam):
		if winUser.isWindowVisible(hwnd):
			windowText = winUser.getWindowText(hwnd)
			# Fast preliminary check using Win32 API before instantiating NVDAObject
			if windowText and windowText.endswith(winTitle):
				try:
					nvdaObj = NVDAObjects.IAccessible.getNVDAObjectFromEvent(
						hwnd,
						winUser.OBJID_CLIENT,
						0
					)
					if mainOnly and nvdaObj:
						if nvdaObj.childCount > 45 :
							o = nvdaObj.getChild(30)
							while o is not None:
								if o.role == controlTypes.Role.GROUPING :
									print("TBirdEnum obj role" + nvdaObj.role.name)
									matchingObjects.append(nvdaObj)
									return False # stops search
								o = o.next
					elif not mainOnly and nvdaObj:
						matchingObjects.append(nvdaObj)
				except Exception:
					# Ignore windows that fail to expose IAccessible interfaces
					pass
		return True

	# Wrap the Python callback with the C ctypes wrapper
	cCallback = WNDENUMPROC(enumWindowsCallback)

	# Call EnumWindows directly via user32 DLL
	user32 = ctypes.windll.user32
	user32.EnumWindows.argtypes = [WNDENUMPROC, wintypes.LPARAM]
	user32.EnumWindows.restype = wintypes.BOOL

	user32.EnumWindows(cCallback, 0)

	return matchingObjects

# import ctypes
# from ctypes import wintypes
# user32 = ctypes.windll.user32
# kernel32 = ctypes.windll.kernel32

# Win32 Constants
# GW_OWNER = 4
#GWL_EXSTYLE = -20
# WS_EX_APPWINDOW = 0x00040000
# SW_SHOW = 5
# SW_RESTORE = 9


# def findMainWindow(winTitle="Mozilla Thunderbird"):
	# """Search and return the handle (hwnd) of the main window

	# whose title contains winTitle. Returns None if not found.
	# """
	# found_hwnd = None

	# # Define callback prototype for EnumWindows
	# WNDENUMPROC = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)

	# def enumWwindowsCallback(hwnd, lparam):
		# nonlocal found_hwnd

		# # 1. The window must be visible
		# if not user32.IsWindowVisible(hwnd):
			# return True

		# # 2. Retrieve window title length
		# length = user32.GetWindowTextLengthW(hwnd)
		# if length == 0:
			# return True

		# # 3. Retrieve window title
		# buffer = ctypes.create_unicode_buffer(length + 1)
		# user32.GetWindowTextW(hwnd, buffer, length + 1)
		# title = buffer.value

		# # 4. Check if title matches
		# if winTitle.lower() in title.lower():
			# # 5. Ensure it is a top-level window (no owner)
			# owner = user32.GetWindow(hwnd, GW_OWNER)

			# # 6. Retrieve extended styles
			# ex_style = user32.GetWindowLongW(hwnd, GWL_EXSTYLE)
			# is_app_window = (ex_style & WS_EX_APPWINDOW) != 0

			# # A main window has no owner OR explicitly sets WS_EX_APPWINDOW
			# if owner == 0 or is_app_window:
				# found_hwnd = hwnd
				# return False  # Stop enumeration (window found)

		# return True  # Continue enumeration

	# # Start window enumeration
	# user32.EnumWindows(WNDENUMPROC(enumWindowsCallback), 0)

	# return found_hwnd

import winUser
import NVDAObjects.IAccessible
def findMainWindow(winTitle="Mozilla Thunderbird"):
	"""Search and return the handle (hwnd) of the main window

	whose title contains winTitle. Returns None if not found.
	"""
	from tones import beep
	beep(250, 50)
	found_hwnd = None

	# Define callback prototype for EnumWindows
	WNDENUMPROC = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)

	def EnumAccWindowsCallback(hwnd, lParam):
		# Filtrer les fenêtres non visibles
		if winUser.isWindowVisible(hwnd):
			try:
				obj = NVDAObjects.IAccessible.getNVDAObjectFromEvent(
					hwnd, 
					winUser.OBJID_CLIENT, 
					0
				)
				if obj:
					# Traitement sur l'objet NVDA (ex: vérifier la classe, le nom, etc.)
					print(f"TBird enum, Fenêtre trouvée : role {obj.role.name} {obj.name} ({obj.windowClassName})")
			except Exception:
				# Certaines fenêtres système ou corrompues peuvent lever des exceptions IAccessible
				pass# 
				print("TBird enum exception")

		return True  # Retourner True pour continuer l'énumération
	# # Start window enumeration
	user32.EnumWindows(WNDENUMPROC(enumAccWindowsCallback), 0)

	return found_hwnd



def restoreAndFocusWindow(hwnd):
	"""Restores the window specified by hwnd and brings it to the foreground."""
	if not hwnd or not user32.IsWindow(hwnd):
		return False

	# 1. Restore the window if minimized, otherwise ensure it is shown
	if user32.IsIconic(hwnd):
		user32.ShowWindow(hwnd, SW_RESTORE)
	else:
		user32.ShowWindow(hwnd, SW_SHOW)

	# 2. Bypass SetForegroundWindow restrictions using AttachThreadInput
	foreground_hwnd = user32.GetForegroundWindow()
	if foreground_hwnd != hwnd:
		current_thread_id = kernel32.GetCurrentThreadId()
		window_thread_id = user32.GetWindowThreadProcessId(foreground_hwnd, None)

		# Temporarily attach input threads if foreground window belongs to a different thread
		if window_thread_id != 0 and current_thread_id != window_thread_id:
			user32.AttachThreadInput(current_thread_id, window_thread_id, True)
			user32.SetForegroundWindow(hwnd)
			user32.BringWindowToTop(hwnd)
			user32.AttachThreadInput(current_thread_id, window_thread_id, False)
		else:
			user32.SetForegroundWindow(hwnd)
			user32.BringWindowToTop(hwnd)

	return True


# Example usage:
if __name__ == "__main__":
	hwnd = findMainWindow("Mozilla Thunderbird")

	if hwnd:
		if restoreAndFocusWindow(hwnd):
			print("Thunderbird restored and brought to foreground.")
		else:
			print("Failed to activate window.")
	else:
		print("Thunderbird window not found.")

# Code Generated by Gemini
import ctypes
from ctypes import wintypes

user32 = ctypes.windll.user32
kernel32 = ctypes.windll.kernel32

# Win32 Constants
GW_OWNER = 4
GWL_EXSTYLE = -20
WS_EX_APPWINDOW = 0x00040000
SW_SHOW = 5
SW_RESTORE = 9


def findMainWindow(winTitle="Mozilla Thunderbird"):
	"""Search and return the handle (hwnd) of the main window

	whose title contains winTitle. Returns None if not found.
	"""
	found_hwnd = None

	# Define callback prototype for EnumWindows
	WNDENUMPROC = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)

	def enum_windows_callback(hwnd, lparam):
		nonlocal found_hwnd

		# 1. The window must be visible
		if not user32.IsWindowVisible(hwnd):
			return True

		# 2. Retrieve window title length
		length = user32.GetWindowTextLengthW(hwnd)
		if length == 0:
			return True

		# 3. Retrieve window title
		buffer = ctypes.create_unicode_buffer(length + 1)
		user32.GetWindowTextW(hwnd, buffer, length + 1)
		title = buffer.value

		# 4. Check if title matches
		if winTitle.lower() in title.lower():
			# 5. Ensure it is a top-level window (no owner)
			owner = user32.GetWindow(hwnd, GW_OWNER)

			# 6. Retrieve extended styles
			ex_style = user32.GetWindowLongW(hwnd, GWL_EXSTYLE)
			is_app_window = (ex_style & WS_EX_APPWINDOW) != 0

			# A main window has no owner OR explicitly sets WS_EX_APPWINDOW
			if owner == 0 or is_app_window:
				found_hwnd = hwnd
				return False  # Stop enumeration (window found)

		return True  # Continue enumeration

	# Start window enumeration
	user32.EnumWindows(WNDENUMPROC(enum_windows_callback), 0)

	return found_hwnd


def restoreAndFocusWindow(hwnd):
	"""Restores the window specified by hwnd and brings it to the foreground."""
	if not hwnd or not user32.IsWindow(hwnd):
		return False

	# 1. Restore the window if minimized, otherwise ensure it is shown
	if user32.IsIconic(hwnd):
		user32.ShowWindow(hwnd, SW_RESTORE)
	else:
		user32.ShowWindow(hwnd, SW_SHOW)

	# 2. Bypass SetForegroundWindow restrictions using AttachThreadInput
	foreground_hwnd = user32.GetForegroundWindow()
	if foreground_hwnd != hwnd:
		current_thread_id = kernel32.GetCurrentThreadId()
		window_thread_id = user32.GetWindowThreadProcessId(foreground_hwnd, None)

		# Temporarily attach input threads if foreground window belongs to a different thread
		if window_thread_id != 0 and current_thread_id != window_thread_id:
			user32.AttachThreadInput(current_thread_id, window_thread_id, True)
			user32.SetForegroundWindow(hwnd)
			user32.BringWindowToTop(hwnd)
			user32.AttachThreadInput(current_thread_id, window_thread_id, False)
		else:
			user32.SetForegroundWindow(hwnd)
			user32.BringWindowToTop(hwnd)

	return True


# Example usage:
if __name__ == "__main__":
	hwnd = findMainWindow("Mozilla Thunderbird")

	if hwnd:
		if restoreAndFocusWindow(hwnd):
			print("Thunderbird restored and brought to foreground.")
		else:
			print("Failed to activate window.")
	else:
		print("Thunderbird window not found.")
		
# import ctypes
# from ctypes import wintypes

# Windows API constants
TH32CS_SNAPPROCESS = 0x00000002
INVALID_HANDLE_VALUE = -1

class PROCESSENTRY32W(ctypes.Structure):
	_fields_ = [
		('dwSize', wintypes.DWORD),
		('cntUsage', wintypes.DWORD),
		('th32ProcessID', wintypes.DWORD),
		('th32DefaultHeapID', ctypes.c_size_t),
		('th32ModuleID', wintypes.DWORD),
		('cntThreads', wintypes.DWORD),
		('th32ParentProcessID', wintypes.DWORD),
		('pcPriClassBase', wintypes.LONG),
		('dwFlags', wintypes.DWORD),
		('szExeFile', ctypes.c_wchar * 260)
	]

def processExists(exeName: str) -> bool:
	"""
	Checks if a process is currently running on Windows.
	:param exeName: Executable file name (e.g., "notepad.exe")
	:return: True if found, False otherwise (case-insensitive)
	"""
	# Take a snapshot of all running processes
	hSnapshot = ctypes.windll.kernel32.CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0)
	if hSnapshot == INVALID_HANDLE_VALUE:
		return False

	try:
		pe32 = PROCESSENTRY32W()
		pe32.dwSize = ctypes.sizeof(PROCESSENTRY32W)

		# Retrieve information about the first process
		if not ctypes.windll.kernel32.Process32FirstW(hSnapshot, ctypes.byref(pe32)):
			return False

		target_name = exeName.lower()

		# Iterate through the process list
		while True:
			if pe32.szExeFile.lower() == target_name:
				return True
			if not ctypes.windll.kernel32.Process32NextW(hSnapshot, ctypes.byref(pe32)):
				break

		return False
	finally:
		# Always close the handle to prevent memory leaks
		ctypes.windll.kernel32.CloseHandle(hSnapshot)
