# code partially generated by gemini
import os
import controlTypes
import tempfile
import globalVars

def getIA2Attr(obj,attribute_value=False,attribute_name ="id"):
	r= hasattr (obj,"IA2Attributes") and attribute_name in obj.IA2Attributes.keys ()
	if not r :return False
	r =obj.IA2Attributes[attribute_name]
	return r if not attribute_value  else r ==attribute_value


class MyLogger:

	def __init__(self, show=False):
		self.show = show
		# Generates: C:\Users\<Username>\AppData\Local\Temp\ThunderbirdPlusLog.txt
		self.logPath = os.path.join(tempfile.gettempdir(), "ThunderbirdPlusLog.txt")		
		self.pFile = None

		bakPath = self.logPath + ".bak"

		# Remove the previous .bak file if it already exists
		if os.path.exists(bakPath):
			try:
				os.remove(bakPath)
			except OSError:
				pass

		# Rename the current log file to .bak if it exists
		if os.path.exists(self.logPath):
			try:
				os.rename(self.logPath, bakPath)
			except OSError:
				pass

		# Create and open the new log file for appending (UTF-8 encoded)
		self.pFile = open(self.logPath, "a", encoding="utf-8")

	def add(self, msg, props=None):
		if self.pFile and not self.pFile.closed:
			if props : msg += str(props) 
			self.pFile.write("\n" + str(msg))
			self.pFile.flush()  # Ensures immediate write to disk
	def addobj(self, obj, lbl) :
		self.add(lbl, props=self.getProperties(obj))
	def getProperties(self, obj) :		
		if not obj : return " object is None"
		focused = ", Focused, " if controlTypes.State.FOCUSED  in obj.states else ""
		name = "no name" if not hasattr(obj, "name") else str(obj.name)
		return " role: {}, ID: {}{}, name: {}".format(obj.role.displayString, str(getIA2Attr(obj)), focused, name)  
			
	def terminate(self):
		if self.pFile and not self.pFile.closed:
			self.pFile.close()

		if self.show and os.path.exists(self.logPath):
			# Opens the log file with the default Windows text editor (Notepad)
			os.startfile(self.logPath)

	def error(self, message):
		print(f"ERROR: {message}")


# global functions
def createLogger(show=False):
		return MyLogger(show=show)

